apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-ovh-access
rules:
  - apiGroups: ["acme.yucelsan.fr"]
    resources: ["ovh"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-ovh-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-ovh-access
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
